import { CalendarDays, Calculator, ChartNoAxesCombined, FileCheck2, FileLock2, FileText, ImageIcon, Landmark, MailCheck, ReceiptText, ScanSearch, ShieldCheck, Truck, Wrench } from "lucide-react";

export const categories = ["All", "Business", "Contractors", "Documents", "Privacy", "Web"];

export const products = [
  { slug: "bidlens", name: "BidLens", value: "Price commercial cleaning work from production assumptions—not gut feel—and turn the result into a client-ready proposal.", audience: "Commercial cleaning owners, estimators, and operators", categories: ["Business"], model: "SaaS subscription or licensed estimator", status: "Interactive demo", signal: "PRICE THE WORK", tone: "cobalt", icon: Calculator, file: "bidlens.html" },
  { slug: "sowguard", name: "SOWGuard", value: "Catch out-of-scope client requests and turn them into clear, priced change orders before free work erodes margin.", audience: "Agencies, contractors, consultants, and project teams", categories: ["Business", "Contractors"], model: "SaaS subscription or team deployment", status: "Interactive demo", signal: "PROTECT MARGIN", tone: "ember", icon: ShieldCheck, file: "sowguard.html" },
  { slug: "nudgeledger", name: "NudgeLedger", value: "See unpaid invoices, understand cash exposure, and generate professional payment follow-ups without losing the thread.", audience: "Freelancers, small agencies, and service businesses", categories: ["Business"], model: "SaaS subscription or one-time desktop license", status: "Interactive demo", signal: "GET PAID", tone: "mint", icon: MailCheck, file: "nudgeledger.html" },
  { slug: "profitpreflight", name: "ProfitPreflight", value: "Review a contractor estimate for missing scope, weak margin, and risky assumptions before the quote reaches the customer.", audience: "Remodelers, roofers, and specialty contractors", categories: ["Contractors", "Business"], model: "Freemium SaaS with trade-specific checks", status: "Interactive demo", signal: "CATCH THE MISS", tone: "violet", icon: FileCheck2, file: "profitpreflight.html" },
  { slug: "pixelgate", name: "PixelGate", value: "Audit marketplace images against Amazon or Etsy requirements, repair common problems, and export compliant assets in batches.", audience: "Marketplace sellers, catalog teams, and product studios", categories: ["Business", "Web"], model: "Paid utility, seller subscription, or agency tool", status: "Local-first demo", signal: "PASS THE GATE", tone: "amber", icon: ImageIcon, file: "pixelgate.html" },
  { slug: "ledgerfold", name: "Ledgerfold", value: "Find which open invoices add up to each bank deposit—even when fees, discounts, or bundled payments complicate the match.", audience: "Bookkeepers, finance teams, and small-business owners", categories: ["Business"], model: "Licensed utility or bookkeeping workflow add-on", status: "Interactive demo", signal: "MATCH THE MONEY", tone: "sky", icon: ReceiptText, file: "ledgerfold.html" },
  { slug: "ironredact", name: "IronRedact", value: "An advanced redaction workspace with searchable-text options and verification reporting, processed in the browser.", audience: "Legal, HR, finance, healthcare, and compliance teams", categories: ["Privacy", "Documents"], model: "One-time license or private team deployment", status: "Browser-processed demo", signal: "REDACT + VERIFY", tone: "steel", icon: FileLock2, file: "ironredact.html" },
  { slug: "blackbar", name: "BlackBar", value: "A focused PDF redaction companion built around batch handling, Bates numbering, pattern scanning, and audit receipts.", audience: "Solo professionals and document-heavy operations", categories: ["Privacy", "Documents"], model: "One-time utility license", status: "Browser-processed demo", signal: "PROVABLE PRIVACY", tone: "ink", icon: ScanSearch, file: "blackbar.html" },
  { slug: "quotefast", name: "QuoteFast", value: "Create polished quotes and invoices quickly, keep client details locally, calculate totals, and print or copy the finished document.", audience: "Independent contractors and mobile service businesses", categories: ["Contractors", "Documents"], model: "Low-cost one-time purchase or freemium utility", status: "Interactive demo", signal: "QUOTE IN MINUTES", tone: "coral", icon: FileText, file: "quotefast.html" },
  { slug: "sitepulse", name: "SitePulse", value: "Turn website performance, SEO, and accessibility signals into a prioritized audit a business owner can act on.", audience: "Web studios, consultants, marketers, and site owners", categories: ["Web", "Business"], model: "Lead-generation audit, SaaS report, or productized service", status: "API-assisted demo", signal: "SEE THE SIGNAL", tone: "lime", icon: ChartNoAxesCombined, file: "sitepulse.html" },
  { slug: "corecred", name: "CoreCred", value: "Track parts returns from the rack through vendor pickup to the actual credit, so repair shops recover every core and warranty dollar.", audience: "Independent auto repair shops, collision centers, and parts desks", categories: ["Business"], model: "Shop subscription or multi-location parts-desk license", status: "Local-first demo", signal: "RECOVER THE CREDIT", tone: "forest", icon: Wrench, file: "corecred.html" },
  { slug: "freightdue", name: "FreightDue", value: "Capture detention, TONU, layover, lumper, and other accessorial revenue with the proof and follow-up needed to get paid.", audience: "Small carriers, owner-operators, dispatchers, and freight billing teams", categories: ["Business"], model: "Per-truck SaaS subscription or recovery-based service", status: "Local-first demo", signal: "BILL THE EXTRAS", tone: "safety", icon: Truck, file: "freightdue.html" },
  { slug: "ledgerlens", name: "LedgerLens", value: "Audit bank and card CSV exports locally to find recurring charges, silent price hikes, duplicates, fees, and spending patterns.", audience: "Small-business owners, freelancers, bookkeepers, and finance consultants", categories: ["Business", "Privacy"], model: "Paid desktop utility or advisor/team license", status: "Browser-processed demo", signal: "AUDIT THE LEDGER", tone: "ocean", icon: Landmark, file: "ledgerlens.html" },
  { slug: "shiftforge", name: "ShiftForge", value: "Build constraint-aware weekly staff rotas that balance coverage, availability, rest, fairness, contracted hours, and wage cost.", audience: "Cafés, restaurants, retail shops, clinics, and other shift-based teams", categories: ["Business"], model: "Per-location subscription or offline team license", status: "Local-first demo", signal: "BUILD THE ROTA", tone: "plum", icon: CalendarDays, file: "shiftforge.html" },
] as const;

export function getProduct(slug?: string) { return products.find((product) => product.slug === slug) ?? products[0]; }
